version: 2
workflows:
  version: 2
  bioeval-flow:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - master

      - tag:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^.*/

bioeval-env: &bioeval-env
  docker:
    - image: circleci/python:3.6.8
  working_directory: ~/project

jobs:
  test:
    <<: *bioeval-env
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            make build
      - run:
          name: Lint
          command: |
            export PATH=/home/circleci/.local/bin:$PATH
            make lint
      - run:
          name: Install
          command: |
            make install
      - run:
          name: Test
          command: |
            export PATH=/home/circleci/.local/bin:$PATH
            make test

  tag:
    <<: *bioeval-env
    steps:
      - checkout
      - run:
          name: Release
          command: |
            make release
